tests/CMakeLists.txt

My next task is addressing all the TODOs in this lib, so this isn't **too** dirty

Temporarily disable test that fails occasionally

---

include/aws/http/connection.h
source/connection.c

User can initiate a connection close.

---

source/websocket_encoder.c
tests/test_websocket_decoder.c
tests/test_websocket_encoder.c

make bit-twiddling code easier to read

---

.clang-tidy
bin/elasticurl/main.c
codebuild/common-posix.sh
source/connection.c
source/connection_h1.c
source/decode.c
source/hpack.c
source/hpack_huffman_static.c
source/http.c
source/request_response.c
source/websocket.c
source/websocket_decoder.c
source/websocket_encoder.c
tests/test_decode.c

assert -> AWS_ASSERT

---

cmake/aws-c-http-config.cmake

I forgot the thing

---

continuous-delivery/build-elasticurl-manylinux-x64.yml

sigh.... this sux.

---

continuous-delivery/build-elasticurl-manylinux-x64.yml

in bash the list arguments need to be quoted.

---

include/aws/http/connection.h

N/A
Update Http Connection Shutdown and Release documentation to explain that calling `aws_http_connection_release()` and `aws_tls_ctx_destroy()` back to back without waiting for the `on_shutdown()` callback to fire may cause Segfaults.

Update Documentation for Http Connection Shutdown and Release

---

include/aws/http/private/hpack.h

fix shared lib builds

---

tests/test_connection_manager.c

Unlock mutex even if early out from connection release function

---

include/aws/http/private/hpack.h

Fix shared lib build

---

include/aws/http/websocket.h
source/websocket.c
tests/CMakeLists.txt
tests/test_websocket_bootstrap.c

aws_websocket_random_handshake_key()

---

source/websocket.c

Websocket Upgrade - Make .c name match .h name

---

bin/elasticurl/main.c
tests/test_connection.c

Update for logging move

---

source/request_response.c
tests/test_connection_manager.c

don't get_length() unless array_list_is_valid()

---

source/request_response.c
tests/CMakeLists.txt
tests/test_request.c

test aws_http_request OOM errors

---

tests/test_websocket_bootstrap.c

Use timebomb allocator from aws-c-common

---

bin/elasticurl/main.c
include/aws/http/private/request_response_impl.h
include/aws/http/private/websocket_impl.h
include/aws/http/request_response.h
include/aws/http/websocket.h
source/h1_connection.c
source/websocket.c
source/websocket_bootstrap.c
tests/test_h1_client.c
tests/test_tls.c
tests/test_websocket_handler.c

Implement auto/manual window updates

---

source/http.c

Remove invalid entry from error list. Relates to PR: https://github.com/awslabs/aws-c-common/pull/454

Fix error list

---

include/aws/http/connection.h
include/aws/http/private/connection_impl.h
include/aws/http/private/h1_stream.h
source/connection.c
source/h1_connection.c
source/h1_stream.c

Implement `aws_h1_stream` in it's own file.
The commits are meant to be reviewed individually, in sequence.

H1b streams

---

source/request_response.c

H1B: header block

---

integration-testing/http_client_test.py

Close files in test script fallback compare

---

source/h1_connection.c
source/h1_encoder.c

CI fixes after merge

---

tests/test_websocket_bootstrap.c

Fixes downstream build failure for base64 append

---

source/connection.c
source/h1_encoder.c
tests/test_h1_client.c
tests/test_h1_server.c

H1B: Fix broken stream API

---

source/hpack.c

Fix 0-length alloc in dynamic table

---

source/hpack.c

trivial hpack error handling

---

source/connection_manager.c

Additional logging and paranoid error handling for connection acquisition.

Better connection acquisition logging and error handling

---

include/aws/http/connection.h
include/aws/http/request_response.h

Document the thread that callbacks will fire on.

---

bin/elasticurl/main.c
source/http.c
tests/proxy_test_helper.c
tests/test_connection.c
tests/test_connection_manager.c
tests/test_h1_client.c
tests/test_h1_decoder.c
tests/test_h1_server.c
tests/test_tls.c
tests/test_websocket_bootstrap.c
tests/test_websocket_decoder.c
tests/test_websocket_encoder.c
tests/test_websocket_handler.c

Update to common/io changes, fix clean_up

---

include/aws/http/connection.h
include/aws/http/connection_manager.h

Const options

---

source/h1_connection.c
tests/test_connection.c
tests/test_h1_server.c

a typo of stream list & potential bug in test connection

---

CMakeLists.txt
cmake/aws-c-http-config.cmake

Fixed dll/.a hell in the same build closure.

---

integration-testing/http_client_test.py

changes to support testing aws-crt-python/elasticurl.py

---

source/h1_connection.c
source/h1_decoder.c

Fixed missing exports of h1 connection.

---

tests/fuzz/fuzz_h2_decoder.c
tests/fuzz/fuzz_h2_frames.c

Fixed tests to match tracer API updates

---

include/aws/http/request_response.h
source/request_response.c
tests/CMakeLists.txt
tests/test_message.c

Can make new request with existing headers

---

include/aws/http/request_response.h

Added missing dll exports.

---

bin/elasticurl/main.c
tests/proxy_test_helper.c
tests/proxy_test_helper.h
tests/test_connection.c
tests/test_connection_manager.c
tests/test_tls.c

Incorporate API changes from https://github.com/awslabs/aws-c-io/pull/215

bootstrap-shutdown-cb: HTTP edition

---

builder.json
integration-testing/http_client_test.py

Also, hide elasticurl output unless test fails

CI wasn't running elasticurl tests.

---

CMakeLists.txt
tests/CMakeLists.txt

enabled in-source builds.

---

source/connection_manager.c
tests/test_proxy.c

Include aws_string

---

cmake/aws-c-http-config.cmake

Fix cmake config template.

---

.github/workflows/ci.yml

Fixed copy pasta from aws-c-io

---

.github/workflows/ci.yml

Get builder from cloudfront

---

CMakeLists.txt

Do not compile elasticurl when cross-compiling

---

include/aws/http/private/hpack.h

Visibility macro for aws_hpack_encode_header_block

---

include/aws/http/private/h2_frames.h

Exported aws_h2_settings_initial

---

include/aws/http/connection.h

Exported get_remote_settings API

---

CMakeLists.txt

CI tests that each public header file is 👍

add header checks to CI

---

include/aws/http/private/connection_manager_system_vtable.h

play nicely with swiftpm not being good at playing with others.

---

include/aws/http/websocket.h

websocket docs typo

---

bin/elasticurl/main.c
tests/proxy_test_helper.c
tests/test_connection.c
tests/test_connection_manager.c
tests/test_tls.c

* Updates test to new host resolver creation signature

resolver creation signature update

---

.github/workflows/ci.yml
CONTRIBUTING.md
README.md
tests/test_h1_client.c

find/replace: master->main

---

tests/test_connection_manager.c

Elg api update for tests

---

bin/elasticurl/main.c
source/http.c
tests/proxy_test_helper.c
tests/test_connection.c
tests/test_connection_manager.c
tests/test_tls.c

* Updates http to use the new managed thread system properly

Thread join

---

integration-testing/http_client_test.py

add timeout for integration test

---

source/h2_connection.c

Fix some warnings

---

.github/workflows/ci.yml

Migrate to ecr and consolidate jobs

---

bin/elasticurl/main.c

Fixed argument parsing for elasticurl.

---

include/aws/http/proxy.h
source/proxy_connection.c

Make proxy options const

---

include/aws/http/private/random_access_set.h
source/random_access_set.c
tests/CMakeLists.txt
tests/test_random_access_set.c

move the https://github.com/awslabs/aws-c-common/pull/883 here as private structure since currently the use case is limited, not worth to make it public. Original review and comments can be fount from https://github.com/awslabs/aws-c-common/pull/883. If anyone in the future needs the data structure outside http, he can continue on the PR in common.

random access set

---

source/h1_encoder.c
source/h2_frames.c
source/http2_stream_manager.c

We still want these sanity checks, even if they're wasted work in release.

Silence "variable set but not used" warnings

---

include/aws/http/connection_manager.h
include/aws/http/http2_stream_manager.h
source/connection_manager.c
source/http2_stream_manager.c
tests/test_connection_manager.c
tests/test_stream_manager.c

- More clear configuration for prior knowledge. More clear validation as well. 

stream manager prior knowledge 

---

source/h2_connection.c
source/h2_stream.c

This code didn't have bugs, but I thought it did, so rewriting to be more clear.
Using simple if/else statements, instead of multiple if's in a row that repeat similar logic.

Edit some code for clarity

---

source/h1_decoder.c

- The s_cat function doesn't check for out_bound when add the two length.
- The function is basically `aws_byte_buf_append_dynamic`
- replace the function with `aws_byte_buf_append_dynamic`

replace s_cat with `aws_byte_buf_append_dynamic`

---

include/aws/http/private/websocket_decoder.h
source/websocket_decoder.c

Adapt to: https://github.com/awslabs/aws-c-common/pull/981

Adapt to renamed class from aws-c-common

---

source/connection.c
source/connection_manager.c
source/h1_connection.c
source/h2_connection.c
source/h2_frames.c
source/http2_stream_manager.c
source/proxy_connection.c
source/request_response.c
source/websocket.c
source/websocket_bootstrap.c
tests/test_connection.c
tests/test_h1_client.c
tests/test_h1_server.c
tests/test_websocket_bootstrap.c
tests/test_websocket_decoder.c
tests/test_websocket_handler.c

https://github.com/awslabs/aws-crt-cpp/issues/330
change #if _MSC_VER to #ifdef _MSC_VER

change #if _MSC_VER to #ifdef _MSC_VER

---

.builder/action/local-server-setup.py

Skip local server setup when tests are disabled

---

CMakeLists.txt
sanitizer-blacklist.txt

Remove sanitizer blacklist, since its currently not used and planned to be removed from common

remove sanitizer blacklist

---

.github/workflows/ci.yml
tests/test_connection_manager.c
tests/test_stream_manager.c

update builder version to fix aws-lc build on manylinux1

---

source/hpack.c
source/http.c

Fix compiler warnings about missing void

---

integration-testing/http_client_test.py
tests/test_connection_manager.c
tests/test_stream_manager.c

- `httpbin` is flaky and abandoned, so move to `postman-echo`.

Move to postman-echo.com from httpbin.org

---

bin/elasticurl/main.c

Preemptively opening a PR here to check/assure that this code isn't really needed/doing anything 😅.

Remove unused headers code in elasticurl

---

.github/workflows/ci.yml
include/aws/http/request_response.h
source/h1_decoder.c
source/h1_encoder.c
source/proxy_connection.c

See: https://github.com/awslabs/aws-c-common/pull/1089

Fix a bunch of places we forget to aws_raise_error()

---

include/aws/http/server.h
source/connection.c
tests/CMakeLists.txt
tests/test_connection.c

API to query http server listener endpoint

---

include/aws/http/connection_manager.h

 Mark the network interface API experimental

---

.github/workflows/stale_issue.yml

update stale issue bot permissions

---

.github/workflows/ci.yml
builder.json

Switch CI to use roles
