bin/elasticurl/main.c
tests/test_connection.c

Updates to client_bootstrap and host resolver from io

---

integration-testing/http_client_test.py

* Changed example.com -> http://example.com: 
* Scheme is required, as per: https://tools.ietf.org/html/rfc3986#page-17
* Added a little framework around the tests, we need to add lots more

Made a proper test suite out of integration tests

---

bin/elasticurl/main.c
continuous-delivery/build-elasticurl-manylinux-x64.yml
continuous-delivery/build-elasticurl-osx.sh
continuous-delivery/build-elasticurl-unix.sh
continuous-delivery/build-elasticurl-win64.sh

Added cd scripts, added version option to elasticurl.

---

include/aws/http/private/h1_decoder.h
include/aws/http/private/http_impl.h
source/h1_connection.c
source/h1_decoder.c
tests/test_h1_decoder.c

* Move the decoder vtable from h1_decoder.h to http_impl.h
* Refactor h1 decoder to operate on byte_cursors.

More HTTP1.1 refactors

---

source/h1_connection.c

return SUCCESS on process read failures so that sender does not try and clean up message

Fix for mem-release crash on h1 decode failure

---

include/aws/http/private/websocket_impl.h
include/aws/http/websocket.h
source/websocket.c
tests/test_websocket_handler.c

This is similar to https://github.com/awslabs/aws-c-http/pull/72
Websocket's `on_connection_shutdown` callback shouldn't fire during the handler shutdown, it should fire during the channel's shutdown.
This change clarified some questions I had about lifetime/ownership (hence the deleted TODOs and modified API comments)

Fix websocket shutdown callback timing.

---

source/connection.c

Edge case was: channel setup succeeded, but something goes wrong creating the HTTP handler. The on_setup() callback should not be invoked until the channel finishes shutting down.

Delay failed setup cb until channel shutdown completes

---

integration-testing/http_client_test.py

Copy/pasted changes from closed PR https://github.com/awslabs/aws-c-http/pull/74 which had  become haunted.
#🚫👻

improve error output when filecmp.cmp() fails

---

include/aws/http/request_response.h
source/request_response.c
tests/CMakeLists.txt
tests/test_request.c

Request object that can be transformed by signers before it's passed to the actual HTTP connection.
Controversial design decisions:
- A million individual string allocations. I could have packed all the string copies into one linear byte_buf, but if that buf ever resized, all the old pointers would suddenly go invalid (rare bugs are best bugs!). We can optimize this with a small-block allocator in the future.
Future work:
- Decide if the transform_request_fn() needs to support asynchronous transforms.
- Decide if there should be some corresponding validate_respones_fn().
- Revamp aws_stream_new_client_request() to take this structure. I didn't want to break the existing API before leaving on vaction.
By submitting this pull request, I confirm that my contribution is made under the terms …

mutable aws_http_request object

---

bin/elasticurl/main.c
include/aws/http/request_response.h

* Use the new aws_http_request mutable struct/API.  
* Move signer-specific details like region and service to a generic context map.

Revamp of elasticurl signing

---

bin/elasticurl/main.c
include/aws/http/http.h
include/aws/http/private/http_impl.h
include/aws/http/private/request_response_impl.h
include/aws/http/request_response.h
include/aws/http/websocket.h
source/h1_connection.c
source/http.c
source/request_response.c
source/websocket.c
source/websocket_bootstrap.c
tests/test_h1_client.c
tests/test_h1_decoder.c
tests/test_request.c
tests/test_tls.c
tests/test_websocket_bootstrap.c

All requests now require that the user create a request object

---

include/aws/http/private/connection_impl.h
include/aws/http/private/h1_encoder.h
include/aws/http/private/request_response_impl.h
include/aws/http/request_response.h
source/h1_connection.c
source/h1_encoder.c
source/h1_stream.c
source/request_response.c
tests/test_h1_server.c

H1B: Use response class instead of response_options

---

bin/elasticurl/main.c
source/connection.c

This is just temp until H1B merges but still.

Remove amount_read param from elasticurl stream

---

bin/elasticurl/main.c
include/aws/http/private/connection_impl.h
include/aws/http/private/h1_stream.h
include/aws/http/private/websocket_impl.h
include/aws/http/request_response.h
source/h1_connection.c
source/h1_stream.c
source/proxy_connection.c
source/request_response.c
source/websocket_bootstrap.c
tests/integration_test_proxy.c
tests/test_h1_client.c
tests/test_proxy.c
tests/test_tls.c
tests/test_websocket_bootstrap.c

One last bit of API breakage before merging H1B. This makes the C impl match more closely with what we ended up with in the bindings.
Look at `request_response.h` to see what actually changed.

H1B: stream::new_client_request() -> connection.make_request()

---

source/hpack.c

This crash was triggering in all of the common and io downstream builds. Look, CI helped us find a bug!

Fix fuzz crash in hpack dyn table

---

bin/elasticurl/main.c
include/aws/http/private/h1_decoder.h
include/aws/http/request_response.h
source/h1_connection.c
source/h1_decoder.c
source/proxy_connection.c
source/websocket_bootstrap.c
tests/integration_test_proxy.c
tests/test_h1_client.c
tests/test_h1_server.c

enum name matches its values
```
enum aws_http_header_block {
AWS_HTTP_HEADER_BLOCK_MAIN,
AWS_HTTP_HEADER_BLOCK_INFORMATIONAL,
AWS_HTTP_HEADER_BLOCK_TRAILING,
}
```

aws_http_header_type -> aws_http_header_block

---

tests/test_h1_client.c
tests/test_h1_server.c

Adapt to changes from https://github.com/awslabs/aws-c-io/pull/187

input-stream destroy

---

source/connection.c

~~`(const char *)aws_string_bytes(some_string)`~~
~~`(const char *)some_string->bytes`~~
`aws_string_c_str(some_string)`

aws_string_c_str()

---

source/h1_connection.c

This was leading to aws-crt-python passing `None` to its on_body callback instead of a byte buffer. Seems better to nip this complexity at the source than in each crt and/or user code.

Don't fire on_body for empty chunks of data

---

.gitignore
include/aws/http/private/hpack.h
source/h2_decoder.c
source/h2_frames.c
source/hpack.c
tests/test_hpack.c

I misread the spec the first time, whoops.

Rewrite HPACK dyn table to have size be in octets instead of elements

---

include/aws/http/private/h2_connection.h
include/aws/http/private/h2_decoder.h
source/h1_connection.c
source/h2_connection.c
source/h2_decoder.c
tests/CMakeLists.txt
tests/test_h2_client.c
tests/test_h2_frames.c
tests/test_h2_headers.c

- flesh out channel handler vtable
- create & destroy encoder & decoder
- test_h2_client.c with 1 test and boilerplate

h2 channel handler boilerplate

---

include/aws/http/private/h2_frames.h
source/h2_decoder.c
source/h2_frames.c
tests/fuzz/fuzz_h2_decoder_correct.c
tests/test_h2_encoder.c
tests/test_h2_headers.c

I found it confusing that the term "header" didn't always refer to HTTP headers.

Use term 'prefix' instead of 'header' for common part of h2 frames

---

include/aws/http/private/h1_decoder.h
include/aws/http/private/http_impl.h
source/h1_connection.c
source/h1_decoder.c
tests/test_h1_decoder.c

We had moved this to a common area when we thought the to-be-built h2 decoder would use the same callbacks. It totally does not.

Move stuff that's specific to h1 decoder into h1_decoder.h

---

include/aws/http/private/h2_decoder.h
include/aws/http/private/h2_frames.h
include/aws/http/private/hpack.h
include/aws/http/request_response.h
source/h2_decoder.c
source/h2_frames.c
source/h2_stream.c
source/hpack.c
source/request_response.c
tests/fuzz/fuzz_h2_decoder_correct.c
tests/test_h2_decoder.c
tests/test_h2_headers.c

Previously, the HPACK compression options were only exposed in private h2 headers.
Now the public `aws_http_header` struct has the option exposed.
Check out the `aws_http_header_compression` enum and tell me what you think of the name and comments. Didn't use the term "hpack" because we'll be using this for HTTP/3 as well, where it's called QPACK (and has even more options, but they're thematically similar).

Add compression options to aws_http_header struct

---

source/h1_connection.c

Fix bug when new request has same memory address as old request.

---

.github/workflows/ci.yml
source/hpack.c

Enabled compilation on VS 2015

---

.github/workflows/ci.yml
include/aws/http/private/h1_encoder.h
include/aws/http/private/http_impl.h
source/h1_connection.c
source/h1_encoder.c
source/h1_stream.c
source/http.c
tests/proxy_test_helper.c
tests/test_connection.c
tests/test_h1_client.c
tests/test_proxy.c
tests/test_websocket_handler.c

Fix proxies connect and tests

---

source/h2_frames.c

Fixed export of aws_h2_connection_preface_client_string

---

include/aws/http/private/h1_decoder.h
include/aws/http/private/h1_encoder.h
include/aws/http/private/h2_decoder.h
include/aws/http/private/h2_frames.h
include/aws/http/private/hpack.h
source/h1_decoder.c
source/h2_decoder.c
source/h2_frames.c
source/hpack.c
tests/h2_test_helper.c
tests/h2_test_helper.h
tests/test_h2_client.c
tests/test_h2_decoder.c

Move code around so we can re-use helpers.
Most of this code was already reviewed here: https://github.com/awslabs/aws-c-http/pull/187
How to review this PR:
- First few files are just adding `const` to arguments
- `h2_test_helper.h/c`
- `struct h2_decoded_frame` used to be `struct frame` in `test_h2_decoder.c`
- `struct h2_decode_tester` used to be `struct fixture` in `test_h2_decoder.c`
- `struct h2_fake_peer` is **NEW**
- `test_h2_client.c`: rewrote one test to use the helpers, instead of comparing against binary data I'd typed out by hand.
- `test_h2_decoder.c`: massive changes not worth looking at, it's just from me moving/renaming the code.

H2 test helper

---

tests/stream_test_helper.c
tests/stream_test_helper.h
tests/test_h1_client.c

- Remove `struct response_tester` from test_h1_client.c
- Rewrite as `struct client_stream_tester` in `stream_test_helper.h/c`
You don't need to look at the billion lines of changed code in `test_h1_client.c`. It's just adapting to the minor API/changes/renames.

Make helper code from `test_h1_client.c` available to h2:

---

tests/CMakeLists.txt

These tests fail occasionally in CI. Deactivate until we resume work on our HTTP server.
The server code has no users and is not bound to any language CRTs. 

Deactivate flaky server tests

---

include/aws/http/request_response.h

Another missing visibility macro

---

bin/elasticurl/main.c

Enable HTTP/2 in elasticurl with `--http2`
ᕕ( ᐛ )ᕗ
We can make HTTP/2 happen by default (alpn="h2;http/1.1") once it's feature-complete. For now its opt-in.

enable http/2 in elasticurl

---

include/aws/http/private/h2_connection.h
include/aws/http/private/h2_stream.h
source/h2_connection.c
source/h2_stream.c
tests/CMakeLists.txt
tests/test_h2_client.c

Until we have a need for it, PUSH_PROMISE is not a fully supported feature. Therefore, promised streams are automatically rejected in a manner compliant with RFC-7540
Why, you ask, don't we simply send SETTINGS_ENABLE_PUSH=0 in the initial SETTINGS frame and call it a day? Because it's theoretically possible for a server to start sending PUSH_PROMISE frames in the initial response, before sending the ACK to the initial SETTINGS.

Automatically reject PUSH_PROMISE streams

---

include/aws/http/private/h2_connection.h
include/aws/http/private/h2_frames.h
include/aws/http/private/h2_stream.h
include/aws/http/private/hpack.h
source/h2_connection.c
source/h2_decoder.c
source/h2_frames.c
source/h2_stream.c
source/hpack.c
tests/test_h2_client.c
tests/test_hpack.c

- settings change from internal.
- create a queue for pending settings
- when we want to change our settings, we send a setting frame to our peer, then push the pending settings to the back of the queue.
- when the setting ACK is received from the peer, we pop the front one from the queue, and apply the settings to our connection.

internal settings change function

---

include/aws/http/private/h2_connection.h
source/h1_connection.c
source/h2_connection.c

- aws_stream_activate() should be increment stream refcount, not the function that moves it to a thread.
- rename `s_stream_activate()` -> `s_move_stream_to_thread()` so it's not confused with `aws_h2_stream_activate()`
- reduce number of times we load atomic `new_stream_error_code`.
- moved atomics out of `synced_data` to reduce confusion

Fix refcounting bug in h2_connection.c

---

source/h2_connection.c

Use high resolution clock instead of system clock to avoid the possible system clock changing.

high res clock instad of sys clock

---

include/aws/http/private/h1_connection.h
source/h1_connection.c

rename `h1_connection` -> `aws_h1_connection`
Doing this so it's easier to share code between h1_connection.c/h1_stream.c. This is part of a larger change, but it's so disruptive I'm breaking it out into its own PR. This is similar to how we do it for h2, so that's nice too.

move h1_connection struct to private .h file

---

include/aws/http/private/h1_connection.h
source/h1_connection.c
tests/test_h1_client.c

Also break up giant process_read_message() function into smaller chunks.
Previously, we were only queueing messages after switching protocols and becoming a midchannel handler. Now we always queue messages before processing them.
This is in preparation for changing how windows work in HTTP/1. We might need to buffer up read messages if the HTTP-stream's window is too small.

HTTP/1 queues all read aws_io_messages before processing.

---

bin/elasticurl/main.c

check the return code first, in case the connection is null

---

source/connection.c

* Split various failure cases into unique logging calls.

Add details to connection option validation failure logging

---

include/aws/http/private/h2_frames.h
source/connection.c
source/connection_manager.c
source/h2_frames.c
source/proxy_connection.c

**Issue:**
Encountered compiler warning [C4232](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4232?view=vs-2019) when building aws-c-http as shared library on Windows:
> nonstandard extension used : 'identifier' : address of dllimport 'dllimport' is not static, identity not guaranteed.
The following definitions are impacted:
```c
/* In connection.c */
static struct aws_http_connection_system_vtable s_default_system_vtable = {
.new_socket_channel = aws_client_bootstrap_new_socket_channel,
};
```
```c
/* In proxy_connection.c */
static struct aws_http_proxy_system_vtable s_default_vtable = {
.setup_client_tls = &aws_channel_setup_client_tls,
};
```
```c
/* In connection_manager.c */
static struct aws_http_connection_manager_system_vtable …
```

Suppress compiler warning C4232 for MSVC

---

include/aws/http/websocket.h

Fix comment that referred to how this API *used to* work

Fix websocket header comment.

---

source/h2_connection.c
source/h2_stream.c

undef debug token before we use it, so swiftpm doesn't break the build.

---

source/proxy_connection.c

* forward port (from ProxyRequestFlow) of tls slot fix when using nested tls

Attach tls handler in proper spot when doing nested tls

---

.github/workflows/ci.yml
tests/test_connection_manager.c

Also fix windows-vc14 (x66) job so it actually uses vc14, and actually builds x86

Add CI jobs for shared-libs

---

tests/test_h1_server.c
tests/test_h2_client.c

The same variable is used in test_h2_client.c and test_h1_server.c file.

tests: Fix multiple definition of s_tester varaible.

---

source/connection_manager.c

To improve debugging, split the error check into three separate checks, each with their own logging. This follows the style specified in c-common.

Add aws_connection_manager_new error logging

---

tests/h2_test_helper.c

related:
https://github.com/awslabs/aws-c-common/pull/808
https://github.com/awslabs/aws-c-io/pull/386

Stop using deprecated aws_off_t

---

.github/workflows/ci.yml
source/websocket.c
source/websocket_encoder.c

GCC doesn't like buffers to be uninitialized before you fill them with random data.

Fix GCC11 warnings

---

include/aws/http/request_response.h
source/request_response.c

Improve ref count semantics on http message

---

source/connection_manager.c
tests/CMakeLists.txt
tests/test_connection_manager.c

- While connection manager is closing, if the culling task runs, it will increase the refcount back from zero, and decrease it after the task, which will let the clean up happen twice.
- A bug while acquire the external refcount should NOT acquire the internal refcount.
- Culling task hold internal refcount, and cancel the task when the external refcount drops to zero instead of the internal refcount.

Fix refcount issue

---

.github/workflows/ci.yml

Fix our CI ignore branches that have / in name
this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Fix our CI ignores branches that have "/" in name

---

include/aws/http/http2_stream_manager.h
tests/CMakeLists.txt
tests/py_localhost/server.py
tests/test_localhost_integ.c
tests/test_stream_manager.c

- Add parallel stress test with body sent
- Updated server implementation to handle multiple streams with body.

Stream manager test with body

---

include/aws/http/connection_manager.h
source/http2_stream_manager.c

- The `aws_http_connection_manager_release_connection` can lead to the callback to be invoked from the same thread, which will lead to a dead lock as we invoked it within a lock.

fix the dead lock for stream manager

---

include/aws/http/private/h2_frames.h
include/aws/http/private/hpack.h
source/h2_decoder.c
source/h2_frames.c
source/hpack.c
source/hpack_decoder.c
source/hpack_encoder.c
tests/fuzz/fuzz_h2_decoder_correct.c
tests/test_h2_headers.c
tests/test_hpack.c

**Issue**:
`aws_hpack_context` did too many things and was difficult to understand.
**Description of changes:**
Sorry, this looks like a lot of new code, but mostly just moving stuff around. Changes are:
- Split `aws_hpack_context` (hpack.c) into 3 classes:
- `aws_hpack_context` (hpack.c) - Still handles dynamic and static table logic.
- `aws_hpack_encoder` (hpack_encoder.c) - Handles encoding of outgoing headers (contains an `aws_hpack_context`)
- `aws_hpack_decoder` (hpack_encoder.c) - Handles decoding of incoming headers (contains an `aws_hpack_context`)
- These structs are now `init()/clean_up()` by-value structs, they used to be `new()/delete()` heap-only structs.
- This avoids an unnecessary allocation (total of 4 per HTTP connection)
- These are package-private structs so don't …

Split up hpack.c

---

bin/elasticurl/main.c
tests/test_connection_monitor.c
tests/test_localhost_integ.c

Issue: Today my Mac started issuing warnings about sprintf().
Changes: Use snprintf() instead.

sprintf() -> snprintf()

---

source/h2_decoder.c

**Issue:**
https://github.com/aws/aws-sdk-cpp/issues/2137
**Description of Changes:**
Rename `decoder_state` -> `h2_decoder_state` to avoid collision with same-named struct in aws-c-compression.

Fix C++ One Definition Rules (ODR) Violations

---

include/aws/http/connection.h
include/aws/http/request_response.h
include/aws/http/websocket.h
source/websocket_bootstrap.c

The WebSocket wasn't using acquire()/release() ref-counting on its HTTP request, because this code was written before we realized ref-counting was a thing we needed to do.
Also, correct a bunch of comments about old-fashioned lifetime management that don't apply now that we ref-count everything.

WebSocket ref-counts its HTTP request

---

include/aws/http/proxy.h
source/proxy_connection.c

- Adds a new function proxy_config new from proxy_options & tls which will be used by `s3_client_new` to make a copy of proxy options.

Add ProxyConfig new from ProxyOptions & TLS info

---

include/aws/http/connection.h
include/aws/http/private/proxy_impl.h
include/aws/http/websocket.h
source/connection.c
source/proxy_connection.c
source/websocket_bootstrap.c

Support for host resolution override per connection

---

.github/workflows/ci.yml
codebuild/linux-integration-tests.yml
include/aws/http/connection.h
include/aws/http/connection_manager.h
include/aws/http/http.h
include/aws/http/http2_stream_manager.h
include/aws/http/proxy.h
include/aws/http/request_response.h
include/aws/http/server.h
include/aws/http/statistics.h
include/aws/http/websocket.h

- Adds `AWS_PUSH_SANE_WARNING_LEVEL` and `AWS_POP_SANE_WARNING_LEVEL` to the public headers. The public header should contain at least one include; otherwise, we will receive a macro not found error. Therefore, I decided to skip adding these macros if there are no includes.

Fix warnings in public headers

---

.github/workflows/ci.yml
codebuild/linux-integration-tests.yml
include/aws/http/request_response.h

Declare `aws_future_http_message`. This will be used by [aws-c-s3](https://github.com/awslabs/aws-c-s3/blob/5849ecfd63d07a37772b9f39194c3b0b49087a6f/source/s3_auto_ranged_put.c#L42)

aws_future<aws_http_message *>

---

.github/workflows/ci.yml

I accidentally changed ci.yml to use "channels"  instead of an official release in my last PR https://github.com/awslabs/aws-c-http/pull/443

use latest aws-crt-builder

---

bin/elasticurl/CMakeLists.txt

- The `target_link_libraries` should be either all-keyworded or non-keyworded. For non-keyworded configurations, there is no default, and it can be either PUBLIC or PRIVATE, depending on various configurations. So, explicitly make it private.
Source: https://cmake.org/pipermail/cmake/2016-May/063400.html

Explicit Private for target_link_libraries

---

include/aws/http/private/connection_impl.h
include/aws/http/private/connection_manager_system_vtable.h
include/aws/http/private/proxy_impl.h
source/connection.c
source/connection_manager.c
source/proxy_connection.c
tests/test_connection_manager.c
tests/test_proxy.c
tests/test_stream_manager.c

*Issue #:* https://github.com/awslabs/aws-c-http/issues/358

system vtables use full function names, for better grepping

---

source/h1_encoder.c

Both of these are sizeof(int), so 4 instead of 1. They are meant to be 1 because they correspond to chars.
As found by DCS `[^._]sizeof[ (]'.{1,2}' filetype:c`
Ref: https://paste.sr.ht/~nabijaczleweli/6ee9ccf301a2651afb693bff46e3671d3f7cdd89
Ref: https://101010.pl/@nabijaczleweli/111587138076843793

sizeof('c')=4, not 1: fix overallocation

---

include/aws/http/request_response.h
source/h2_connection.c
tests/test_h1_client.c
tests/test_h2_client.c

correct the doc about unactivated stream and add test

---

.github/workflows/ci.yml
include/aws/http/private/h1_connection.h
source/h1_connection.c
source/websocket.c
tests/CMakeLists.txt
tests/test_connection.c
tests/test_tls.c

Change the HTTP/1 connection and websocket to adapt the change from TLS deliver the buffered data during shutdown
- In case of user initial the shutdown process, to prevent hanging, open up the flow control window to max to keep the data flow, but as read has stopped, drop anything from TLS directly. 
No need for HTTP/2, since HTTP/2 has it own flow-control method, and not using the channel flow control.
Other unrelated changes:
- We previously disabled the TLS test for Mac because of https://github.com/actions/runner-images/issues/3861
- After GitHub fixed the issue, we brought back one test but forgot the other one https://github.com/awslabs/aws-c-http/pull/329
- Bring back the test, which should be not skipped now.
- MacOS 11 is gone for github runner image. 
TODO:
- HTTP/1 also has …

adapt change from "TLS deliver buffer data during shutdown"

---

integration-testing/http_client_test.py

- On CI like armv7, we need qenum, which makes the program reaaaaaaalllllyyyyy slow. https://github.com/awslabs/aws-crt-java/actions/runs/10853091537/job/30125644849, it hits the timeout couple times, and the whole test took 2 hours to run. Bump it up just. 

increase timeout for http integration tests

---

source/h1_connection.c
source/http.c

Tweak error message for AWS_ERROR_HTTP_RESPONSE_FIRST_BYTE_TIMEOUT

---

include/aws/http/private/hpack.h

*Issue #, if available:* 
https://github.com/awslabs/aws-crt-swift/pull/294
*Description of changes:* 
* Excluded the enum definition out of struct, which adds CXX interoperability support for `aws-crt-swift`.

Add cxx support

---

.github/workflows/ci.yml

See Issue: https://github.com/llvm/llvm-project/issues/59007. Although this issue has been fixed in LLVM, the fix will not probably propagate to older versions of Ubuntu and GCC-13.1.
Starting with GLIBC version 2.34, the `dn_expand` function, previously found in `libresolv.so`, was moved to `libc.so`. This function is used internally by the `getaddrinfo()` system call.
In our setup, we are using an Ubuntu 18 Docker image on a newer Ubuntu host. However, due to compatibility issues between newer libasan.so in GCC 13.1 and the older Ubuntu image, the linker does not link with `libresolv.so`. This results in crashes in `getaddrinfo()`.
This problem does not occur on Ubuntu 22 and newer because GLIBC versions 2.34 and above include `dn_expand` in `libc.so`, eliminating the dependency on …

Fix CI for GCC-13 on Ubuntu-18 

---

include/aws/http/private/h1_stream.h
source/h1_connection.c
source/h1_stream.c
tests/test_connection_manager.c
tests/test_localhost_integ.c
tests/test_stream_manager.c

Some cleanup before embarking on major plumbing...
While developing HTTP/1, we stumbled into the pattern of grouping variables under `thread_data` or `synced_data`, so it was more explicit how they should be accessed. But we never moved ALL the variables into the proper groups. We had a TODO about this. Now it is TODONE.
Also: Fix some flaky integration tests by accepting any "2xx" status-code, not just literal "200. I observed these tests failing when they sometimes got 202, instead of 200: h2_sm_acquire_stream & h2_sm_acquire_stream_multiple_connections. But I applied the same fix to any other test I found that strictly checked for 200.

Move h1_stream variables, to make thread usage more explicit

---

include/aws/http/connection_manager.h
source/connection_manager.c

We need to bind this value to Java; however, Java only supports the HttpConnectionManager. So add this value as an option to ConnectionManager as well.

Supprt response_first_byte_timeout_ms in ConnectionManagerOptions
